spring.application.name=order-service
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# User Service Configuration
user-service.base-url=http://localhost:8080

# Feign Configuration
feign.client.config.default.connect-timeout=2000
feign.client.config.default.read-timeout=3000
feign.client.config.default.logger-level=full

# Logging Configuration
logging.level.com.siddardha.orderservice.client=DEBUG
logging.level.feign=DEBUG